# Generated by Django 5.1.1 on 2024-10-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
